### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by pramithready** [rhu003/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - We want to see a markdown formatted link in your report. For example you could provide a formatted link to download VS Code at the beginning.
- [x] All relevant code examples written with backticks (```)
  - Make sure to format all the terminal commands in your report with backticks, like `ls`, `scp`, etc
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - You should use markdown headers to separate the individual sections of this report
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - We want to see you run a command remotely and count the number of keystrokes it took to run that command as optimally as possible
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Nice job fixing the previous issues!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by pramithready** [comment]
Great progress and nice work making the previous fixes! Check the comments under each checkbox to see what you need to fix to get full credit!

**Comment by rhu003** [comment]
I actually don't know how to fix the keystrokes part yet, but I fixed some other issues that were unchecked,
