### ISSUE TITLE
Lab Report 4 Feedback 

### ISSUE THREAD

**Issue by enzohnnn** [rhu003/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
You showed a screenshot of the snippets but didn't really show anything else.

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by rhu003** [comment]
Hi, I actually can't yet submit regrade request on gradescope yet, the status of it is still ungraded

**Comment by rhu003** [comment]
Hi can you take a look at my lab report 4 now and see if I have my checkmarks fixed? I just have my report edited.

**Comment by rhu003** [comment]
Hi Enzo, can you take a look at my report 4 tonight by any chance? I tried my best to fix all the checkmarks but I just wanna know if I need further fixes cuz like tomorrow is the last day to submit regrade so I would really appreciate if you can take a look and provide new feedback today.

**Comment by enzohnnn** [comment]
Well done!

**Comment by enzohnnn** [comment]
Done!
