### ISSUE TITLE
Lab Report 5 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [rhu003/cse15l-lab-reports#5]
Here is your feedback for Lab Report 5:

- [x] Explains how tests with different results were found (`diff`, manual search, etc)

Test 1:

- [ ] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [ ] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Test 2:

- [ ] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [ ] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Additional comments from your grader:
-Include what would be the expected output for each file
-Please talk about what the bug in the code for one of the implementations are, as well as how you can fix it for both test cases

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by rhu003** [comment]
I think I just fixed the issues, please take a look when not so busy.

**Comment by rhu003** [comment]
hi also the status of it on gradescope is still ungraded

**Comment by yahmad3495** [comment]
Looks good! I've updated your score to be full points on gradescope.
